title: MHS Coding Club Workshop
author:
  name: MHS Coding Club
  email: codingmhs@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  MHS Coding Club's web-development workshop

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
remote_theme: pages-themes/hacker@v0.2.0

plugins:
- jekyll-remote-theme

minima:
  # social_links:
     - { platform: github,         user_url: "https://github.com/jekyll/minima" }
     - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
     - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

show_excerpts: false
